### ISSUE TITLE
Can't pass differing feature sets to primary/secondary

### ISSUE THREAD

**Issue by anpatton** [anpatton/lrboost#3]
Allow for passing categorical/nan features into the gbdt part, without breaking ridge

**Comment by bbstats** [comment]
[ColumnTransformer](https://scikit-learn.org/stable/modules/generated/sklearn.compose.ColumnTransformer.html) can do this out of the box, though we could at the very least provide an example on how to do so.

As is the same with much of the parameters in LRBoost, things get really dicey when you start breaking things out of sklearn default behavior. 

I think in general people should be very explicit when writing their model code (e.g. using ColumnTransformer to do it manually), but we could theoretically pass a `no_na_primary=False` and `no_cat_primary=False` into the class constructor if we really wanted to.

**Comment by anpatton** [comment]
Yeah part of me says this is a "do it manually" thing, but also it seems like it's a common enough thing we might want to do it?

**Comment by bbstats** [comment]
My personal preference is to correctly impute NAs (I don't even love how tree methods account for NA), and just one-hot-encode (or target-encode) categoricals for linear, so I don't love just ignoring them. But I understand there are tradeoffs in either direction.

**Comment by anpatton** [comment]
Personally, I think if people want to impute there are enough nuances there they can do it by hand as needed. I do like at least the minimally invasive option of "ohe=True" or whatever

**Comment by bbstats** [comment]
Idk why I'm being stubborn about this. Let's just do this:

1. Make a dictionary arg in the fit function: `feature_sets` e.g. `feature_sets = {'primary_features': [...], 'secondary_features': [...]}`
3. If `feature_sets` is not `None`, we will check that the X passed is a dataframe (if not, raise an error)
4. If `feature_sets` is not `None`, correctly index the features based on the dataframe for each step.

Later on we can add numpy array functionality by allowing for lists/arrays of integer indices etc.
